# Array creation

In [1]:
import numpy as np

In [5]:
arr1 = np.arange(10)

In [6]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#checking the attributes of the one dimensional array

arr1.size

10

In [8]:
arr1.shape

(10,)

In [10]:
arr1.dtype

dtype('int32')

In [9]:
arr1.ndim

1

# 2 D Arrays

In [11]:
# using list of list

In [13]:
m = [0,1,2,3],[0,1,2,3]

In [15]:
arr2 = np.array(m)

In [17]:
arr2

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [18]:
arr2.shape

(2, 4)

In [19]:
arr2.size #total num of elements in the array

8

In [20]:
arr2.ndim

2

In [21]:
alpha = ['a','b','c'],['a','b','c'],['a','b','c']

In [23]:
arr3 = np.array(alpha)

In [24]:
arr3

array([['a', 'b', 'c'],
       ['a', 'b', 'c'],
       ['a', 'b', 'c']], dtype='<U1')

In [25]:
arr3.shape #(rows,coln)

(3, 3)

In [26]:
arr3.size

9

In [27]:
arr3.ndim

2

In [28]:
arr4 = np.arange(15)

In [30]:
arr4.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
arr4.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
arr4.reshape(1,15) #row vector

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [33]:
arr4.reshape(15,1) #coln vector

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [50]:
arr7 = np.arange(10,20,.1) #stepsize

In [51]:
len(arr7)

100

In [52]:
arr7.size

100

In [47]:
arr8 = np.linspace(10,20,30) #total points 30

In [48]:
arr8

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [49]:
arr8.size

30

In [57]:
a = np.arange(70,99,2) #last value is not inlcluded
a.size

15

In [54]:
b = np.linspace(70,99,15) #last value is  inlcluded
b.size

15

In [58]:
b

array([70.        , 72.07142857, 74.14285714, 76.21428571, 78.28571429,
       80.35714286, 82.42857143, 84.5       , 86.57142857, 88.64285714,
       90.71428571, 92.78571429, 94.85714286, 96.92857143, 99.        ])

In [59]:
a

array([70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Initial Placeholder

In [60]:
# zeros

In [61]:
np.arange(3)

array([0, 1, 2])

In [62]:
np.zeros(3)

array([0., 0., 0.])

In [66]:
np.zeros(15).reshape(5,3,1)

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [67]:
# ones

In [68]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.ones(20).reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
# identity matrix

In [74]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [73]:
np.diag([11,22,33])

array([[11,  0,  0],
       [ 0, 22,  0],
       [ 0,  0, 33]])