#  Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1[0] #array_name[index position]

0

In [5]:
arr1[5]

5

In [6]:
arr2 = np.arange(5,15)

In [7]:
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr2[5]

10

In [10]:
arr2[5:11] #array_name[start :end]

array([10, 11, 12, 13, 14])

In [11]:
arr2[5:] #array_name[start :end]

array([10, 11, 12, 13, 14])

In [12]:
list_num = [11,22,33,44,55]

In [14]:
list_num[0]

11

In [16]:
list_num[:3]

[11, 22, 33]

In [17]:
list_num[1:]

[22, 33, 44, 55]

In [18]:
list_num[:]

[11, 22, 33, 44, 55]

In [19]:
list_num[::-1]

[55, 44, 33, 22, 11]

In [20]:
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr2[:4]

array([5, 6, 7, 8])

In [22]:
# 2D Arrays

In [25]:
arr4 = np.arange(15).reshape(5,3)

In [26]:
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
arr4.ndim

2

In [36]:
arr4[1]

array([3, 4, 5])

In [39]:
arr4[4]

array([12, 13, 14])

In [44]:
arr4[2][1]

7

In [46]:
arr4[2,1]

7

In [47]:
arr4[2,0]

6

In [48]:
arr4[4,2]

14

In [50]:
arr5 = np.arange(50).reshape(10,5)

In [51]:
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [52]:
arr5[0,1]

1

In [53]:
arr5[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
arr5[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [55]:
arr5[1:2,2:]

array([[7, 8, 9]])

In [59]:
arr6 = np.arange(10,100,10).reshape(3,3)

In [60]:
arr6.size

9

In [61]:
arr6

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
# arr6[rows,coln] #70 80
arr6[2,0:2]

array([70, 80])

In [64]:
# arr6[rows,coln] #30 60
arr6[0:2,2]

array([30, 60])