# Boolean Masking in arrays

# fancy Indexing

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(12).reshape(3,4)

In [3]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
list_num = [10,58,75]
# list_num > 35 not supported error

for i in list_num:
    print(i>35)

False
True
True


In [9]:
arr2 = np.array(list_num)

In [10]:
arr2

array([10, 58, 75])

In [11]:
arr2>35

array([False,  True,  True])

In [12]:
arr2<35

array([ True, False, False])

In [15]:
arr1 % 2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [16]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr1 % 3 == 0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [18]:
(arr1 % 2 == 0) & (arr1 % 3 == 0)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [19]:
(arr1 % 2 == 0) | (arr1 % 3 == 0)

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [20]:
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [21]:
arr1[arr1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [22]:
div_2_3 = (arr1 % 2 == 0) & (arr1 % 3 == 0)#saving the mask in a variable

In [24]:
arr1[div_2_3]

array([0, 6])

# Universal function

In [25]:
emp_sal = [11000,22000,44000]

In [26]:
for i in emp_sal:
    print(i+5000)

16000
27000
49000


In [27]:
emp_sal+5000

TypeError: can only concatenate list (not "int") to list

In [28]:
arr3 = np.array(emp_sal)

In [29]:
arr3+5000

array([16000, 27000, 49000])

In [30]:
arr3-5000

array([ 6000, 17000, 39000])

In [31]:
arr3*1.2 #20% sal increment

array([13200., 26400., 52800.])

In [32]:
arr3/1000

array([11., 22., 44.])

In [33]:
arr3/12 # annual to monthly 

array([ 916.66666667, 1833.33333333, 3666.66666667])

In [34]:
list_val = [11,22,33,'a','b']
arr5 = np.array(list_val)

In [35]:
arr5

array(['11', '22', '33', 'a', 'b'], dtype='<U11')

In [37]:
# arr5/2 #  not supported error