# Universal functions

In [3]:
#also called as ufunc

In [1]:
# on 1d array

In [4]:
import numpy as np

In [5]:
arr1 = np.arange(15)

In [6]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr1 + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114])

In [8]:
arr1 - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86])

In [10]:
arr1/arr1 #Division by zero is possible in numpy

C:\Users\RAHUL\AppData\Local\Temp\ipykernel_31264\1749041114.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr1/arr1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

# aggregate functions

In [11]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.sum(arr1)

105

In [13]:
np.mean(arr1)

7.0

In [14]:
np.min(arr1)

0

In [15]:
np.max(arr1)

14

In [16]:
arr2 = np.linspace(10,15,15)

In [17]:
arr2

array([10.        , 10.35714286, 10.71428571, 11.07142857, 11.42857143,
       11.78571429, 12.14285714, 12.5       , 12.85714286, 13.21428571,
       13.57142857, 13.92857143, 14.28571429, 14.64285714, 15.        ])

In [19]:
np.mean(arr2)

12.5

In [2]:
# on 2d arrys

In [21]:
arr3 = np.arange(15).reshape(5,3)

In [22]:
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
arr3.ndim

2

In [26]:
np.sum(arr3,axis=1)

array([ 3, 12, 21, 30, 39])

In [27]:
np.sum(arr3,axis=0)

array([30, 35, 40])

In [28]:
np.max(arr3,axis=1)

array([ 2,  5,  8, 11, 14])

In [29]:
np.max(arr3,axis=0)

array([12, 13, 14])

In [30]:
np.min(arr3,axis=0)

array([0, 1, 2])

In [31]:
np.mean(arr3,axis=0)

array([6., 7., 8.])

In [32]:
np.mean(arr3,axis=1)

array([ 1.,  4.,  7., 10., 13.])

# Logical Functions

In [33]:
# any | T/F
# all | T/F

In [40]:
arr5=np.array([0,0,0,0,1])

In [41]:
arr5

array([0, 0, 0, 0, 1])

In [42]:
np.any(arr5)

True

In [48]:
arr5=np.array([0,0,0,0,3.14])

In [49]:
np.any(arr5)

True

In [46]:
arr6=np.array([0,0,0,0,77])

In [47]:
np.all(arr6)

False

In [52]:
arr6=np.array([11,22,33,0,77])

In [53]:
np.all(arr6)

False