In [1]:
import numpy as np

# Split

In [2]:
x = np.arange(9)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x.ndim

1

In [5]:
x.shape

(9,)

In [12]:
# datatypes refresh
s = (33+33)-(66*2)+(12*12-9)
print(type(s))

tup = (33,)
print(type(tup))

<class 'int'>
<class 'tuple'>


In [13]:
print(0.1+0.2)

0.30000000000000004


In [14]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [16]:
np.split(x,9)

[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8])]

In [17]:
# splitting a 2d array 

In [18]:
y = np.arange(20).reshape(4,5)

In [19]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
np.split(y,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [24]:
np.split(y,2,axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [25]:
z = np.arange(25).reshape(5,5)

In [26]:
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
np.split(z,5,axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20]]),
 array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [29]:
np.split(z,5,axis=0)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

# copy

In [30]:
a = np.arange(10).reshape(5,2)

In [31]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
b = a

In [33]:
print(id(a))
print(id(b))

2131701374864
2131701374864


In [34]:
c = a.copy()

In [36]:
print(id(c))
print(id(a))

2131703251760
2131701374864


# micro Project

In [43]:
data  = np.loadtxt('fitbit.txt',dtype='str')

In [44]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [45]:
type(data)

numpy.ndarray

In [46]:
data.ndim

2

In [47]:
data.shape

(26, 7)

In [48]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [49]:
data[1]

array(['07-10-2017', '7167', '200', '208', '6', '0', '68'], dtype='<U10')

In [50]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [53]:
date = data.T[0]

In [54]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [55]:
step_count =data.T[1]

In [56]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [57]:
tup1 = (11,22,3,44,55)

In [58]:
a,b,c,d,e = tup1 #tuple unpacking

In [59]:
a

11

In [60]:
b

22

In [61]:
c

3

In [62]:
d

44

In [64]:
date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg = data.T

In [65]:
calories_burned

array(['181', '208', '341', '190', '307', '302', '198', '201', '195',
       '327', '331', '318', '344', '204', '180', '201', '329', '315',
       '197', '184', '328', '322', '327', '148', '235', '184'],
      dtype='<U10')

In [67]:
step_count.dtype

dtype('<U10')

In [68]:
date.dtype

dtype('<U10')

In [70]:
step_count = np.array(step_count,dtype='int')

In [72]:
step_count.dtype

dtype('int32')

In [73]:
calories_burned = np.array(calories_burned,dtype='int')
hours_of_sleep = np.array(hours_of_sleep,dtype='int')
weight_kg = np.array(weight_kg,dtype='int')

In [74]:
hours_of_sleep

array([6, 6, 5, 8, 5, 5, 8, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 8, 8, 5, 5,
       5, 8, 6, 6])

In [76]:
weight_kg.dtype

dtype('int32')

In [77]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [78]:
# gender M/F   1/0   T/F 1/0

In [79]:
# 100 = sad
# 200 = neutral
# 300 = happy